language: perl
# Use container-based infrastucture on Travis which doesn't support running
# things as root; see http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
perl:
    - "5.22"
addons:
    hosts:
        - jobscheduler.local
    apt:
        # Whitelist: https://github.com/travis-ci/apt-source-whitelist
        sources:
            # We need an up-to-date version of Gearman
            - gearman-developers
        # Whitelist: https://github.com/travis-ci/apt-package-whitelist
        packages:
            - gearman
            - gearman-job-server
            - gearman-tools
            - libgearman-dev
            - libgearman7
before_install:
    # Install test coverage reporting tool
    - cpanm Devel::Cover::Report::Coveralls
install:
    # Install Perl dependencies
    - cpanm --installdeps .
before_script:
    - sudo mkdir /var/log/gjs
    - sudo chown travis /var/log/gjs
script:
    - perl Makefile.PL
    - make
    - cover -test -report coveralls
    - make install
