language: perl
perl:
    - "5.16"
    - "5.18"
    - "5.19"
before_install:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
install:
    - sudo apt-get -y install openjdk-7-jdk maven
    - cpanm --verbose --installdeps .
script:
    - perl Makefile.PL
    - make
    - make test
    - make install
