language: perl
# Use container-based infrastucture on Travis which doesn't support running
# things as root; see http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
perl:
    - "5.22"
addons:
    hosts:
        - jobscheduler.local
before_install:
    # Install test coverage reporting tool
    - cpanm Devel::Cover::Report::Coveralls
install:
    # Apt's version of Gearman is too old
    - sudo apt-get -y remove gearman gearman-job-server gearman-tools libgearman-dbg libgearman-dev libgearman-doc libgearman6
    # Install Gearman from PPA repository
    - sudo apt-get -y install python-software-properties
    - sudo add-apt-repository -y ppa:gearman-developers/ppa
    - sudo apt-get -y update
    - sudo apt-get -y install gearman-job-server gearman-tools libgearman-dev
    # Install Perl dependencies
    - cpanm --installdeps .
before_script:
    - sudo mkdir /var/log/gjs
    - sudo chown travis /var/log/gjs
script:
    - perl Makefile.PL
    - make
    - cover -test -report coveralls
    - make install
