language: perl
perl:
    - "5.16"
    - "5.18"
    - "5.19"
before_install:
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
install:
    # Apt's version of Gearman is too old
    - sudo apt-get -y remove gearman gearman-job-server gearman-tools libgearman-dbg libgearman-dev libgearman-doc libgearman6
    # Install Gearman from PPA repository
    - sudo apt-get -y install python-software-properties
    - sudo add-apt-repository -y ppa:gearman-developers/ppa
    - sudo apt-get -y update
    - sudo apt-get -y install gearman-job-server gearman-tools libgearman-dev
    - cpanm --verbose --installdeps .
script:
    - perl Makefile.PL
    - make
    - make test
    - make install
