language: perl
# Use container-based infrastucture on Travis which doesn't support running
# things as root; see http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
perl:
    - "5.22"
addons:
    hosts:
        - jobscheduler.local
    apt:
        # Whitelist: https://github.com/travis-ci/apt-source-whitelist
        sources:
            # We need an up-to-date version of Gearman
            - gearman-developers
        # Whitelist: https://github.com/travis-ci/apt-package-whitelist
        packages:
            - gearman
            - gearman-job-server
            - gearman-tools
            - libgearman-dev
            - libgearman7
env:
    global:
        # Where to write logs
        - GJS_WORKER_LOG_DIR=~/gearman-jobscheduler-logs/
before_install:
    # Install test coverage reporting tool
    - travis_retry cpanm --notest Devel::Cover::Report::Coveralls
install:
    # Install Perl dependencies
    - travis_retry cpanm --installdeps --notest .
script:
    - perl Makefile.PL
    - make
    - cover -test -report coveralls
    - make install
