language: perl
# RabbitMQ requires to setuid
sudo: true
perl:
    - "5.22"
services:
    - rabbitmq
addons:
    hosts:
        - jobscheduler.local
    apt:
        # Whitelist: https://github.com/travis-ci/apt-source-whitelist
        sources:
            # We need an up-to-date version of Gearman
            - gearman-developers
        # Whitelist: https://github.com/travis-ci/apt-package-whitelist
        packages:
            - gearman
            - gearman-job-server
            - gearman-tools
            - libgearman-dev
            - libgearman7
            - rabbitmq-server
before_install:
    # Start RabbitMQ
    - sudo service rabbitmq-server start
    # Install test coverage reporting tool
    - travis_retry cpanm --notest Devel::Cover::Report::Coveralls
install:
    # Install Perl dependencies
    - travis_retry cpanm --installdeps --notest .
script:
    - perl Makefile.PL
    - make
    - make install
    - cover -test -report coveralls
