---
name: Gearman-JobScheduler
version: "0.16.1"
author:
  - 'Linas Valiukas <linas dot valiukas at gmail dot com>'
abstract: Gearman job scheduler
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/pypt/p5-Gearman-JobScheduler
requires:
  Capture::Tiny: 0,
  Carp: 0,
  Data::Compare: 0,
  Data::Dumper: 0,
  Data::UUID: 0,
  DateTime: 0,
  Email::MIME: 0,
  Email::Sender::Simple: 0,
  File::Path: 0,
  File::Slurp: 0,
  File::Temp: 0,
  Gearman::XS: 0,
  IO::File: 0,
  IO::Socket::INET: 0,
  JSON: 0,
  Log::Log4perl: 0,
  Modern::Perl: 0,
  Moose: 2.1005,
  Moose::Role: 2.1005,
  MooseX::Singleton: 0,
  Net::Telnet: 0,
  Proc::Background: 0,
  Readonly: 0,
  Sys::Hostname: 0,
  Test::More: 0
  Test::NoWarnings: 0
  Test::Strict: 0
  Time::HiRes: 0,
  perl: 5.12.0
provides:
  Gearman::JobScheduler:
    file: lib/Gearman/JobScheduler.pm
    version: "0.16.1"
  Gearman::JobScheduler::AbstractFunction:
    file: lib/Gearman/JobScheduler/AbstractFunction.pm
    version: "0.16.1"
  Gearman::JobScheduler::Admin:
    file: lib/Gearman/JobScheduler/Admin.pm
    version: "0.16.1"
  Gearman::JobScheduler::Configuration:
    file: lib/Gearman/JobScheduler/Configuration.pm
    version: "0.16.1"
  Gearman::JobScheduler::Worker:
    file: lib/Gearman/JobScheduler/Worker.pm
    version: "0.16.1"
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
